# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateTimeField(verbose_name='entry time')),
                ('exit', models.DateTimeField(verbose_name='exit time')),
            ],
        ),
    ]
